### ISSUE TITLE
Typo in `_informDipatcherRenderIsDone`

### ISSUE THREAD

**Issue by Swiip** [FBerthelot/component-test-utils#5]
https://github.com/FBerthelot/component-test-utils/blob/master/packages/component-test-utils-react/src/dispatcher/index.js#L22

An `s` is missing  in dispatcher.

**Comment by FBerthelot** [comment]
`_informDipatcherRenderIsDone` should be replace by `_informDipatchersRenderIsDone` ?

Is sound weird to me. Are you sure ?

**Comment by Swiip** [comment]
nop `_informDi` -->s<-- `patcherRenderIsDone`

**Comment by FBerthelot** [comment]
Damn dyslexia strike again
